name: Release module version

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: te9no/zmk-actions/.github/workflows/upgrade-module.yml@v1
